using Newtonsoft.Json;

namespace Korn.Utils.GithubExplorer
{
    /* Autogenerated by: https://github.com/Yoticc/JsonMappingsGenerator */
    public class RepositoryEntryJson
    {
        [JsonProperty("name")] public string Name;    
        [JsonProperty("path")] public string Path;    
        [JsonProperty("sha")] public string Sha;    
        [JsonProperty("size")] public long Size;    
        [JsonProperty("url")] public string Url;    
        [JsonProperty("html_url")] public string HtmlUrl;    
        [JsonProperty("git_url")] public string GitUrl;    
        [JsonProperty("download_url")] public object DownloadUrl;    
        [JsonProperty("type")] public string Type;
        [JsonProperty("_links")] public LinksData Links;

        public string GetDownloadUrl() => DownloadUrl as string;

        public class LinksData
        {
            [JsonProperty("self")] public string Self;
            [JsonProperty("git")] public string Git;
            [JsonProperty("html")] public string Html;
        }
    }
}